### ISSUE TITLE
Close a Modal

### ISSUE THREAD

**Issue by andrewreal** [sharu725/sv-popup#2]
Is there a way to close an open Modal from an event?

I have a modal that has a button which does an action and I'd like to close the modal at the same time as the action happens to save the user having to manually close the model, is this possible?

```
<script>
    import { Modal, Content, Trigger}  from "sv-popup";

    function selectOption(name, value) {
        questions.setValue(name, value);
    }
</script>

<Modal class="description" basic>
    <Trigger>
        <div class="btn">
            i
        </div>
    </Trigger>
    <Content 
        class="{option.alert}"
        >
        {@html option.description}
        <button class="set-value" on:click={() => selectOption(name, option.value)}>Select this option</button>
    </Content>
</Modal>
```

**Comment by sharu725** [comment]
@andrewreal please update the package. I have added a prop called ``close`` which can be passed to the <Modal> and can be triggered externally.


```svelte
<script>
 let closeModal = false; // if it is true then the modal closes
</script>

<Modal close={closeModal}>
  <Content>
    <h1>Hello</h1>
  </Content>
  <Trigger>
    <button>Open Modal</button>
  </Trigger>
</Modal>
```

**Comment by andrewreal** [comment]
@sharu725 Thanks so much, it works perfectly.

Just to add in case anyone else refers to this in the future, in the example code above, if the modal is opened and closed from this function and then opened again it will not close again from this function as `close` is already set to true.

Adding this handler to the Trigger resets the `close` prop.

```
<script>
    function resetOpenState() {
        closeModal = false;
    }
</script>

<Modal close={closeModal}>
  <Content>
    <h1>Hello</h1>
  </Content>
  <Trigger>
    <button on:click={() => resetOpenState()}>Open Modal</button>
  </Trigger>
</Modal>
```
