### ISSUE TITLE
Set the <Trigger> outside from the <Modal> component

### ISSUE THREAD

**Issue by artneo-io** [sharu725/sv-popup#4]
Awesome popup/modal solution for Svelte, thanks a lot!

Is it possible to set an ID to the modal so it's possible to set the <Trigger> outside from the <Modal> component?

Thanks! 🙂

**Comment by artneo-io** [comment]
Nevermind, there's already a simple fix for this issue by using the native `bind:this` Svelte directive

**Comment by jnikula** [comment]
@artneo7 I'm interested in this, care to elaborate?

@sharu725 I'd like to maintain the whole `<Modal>` outside of the other components, and trigger it from JavaScript via `on:click`. Putting the `<Modal>` inline unfortunately messes up my CSS, and anyway I'd like to trigger the same modal from multiple places. An example for this would be nice.

**Comment by gotling** [comment]
@jnikula: I am not sure if this is the solution @artneo-io  came up with but I managed with:

```svelte
<script>
let trigger;
</script>

<Modal>
  <Trigger>
    <button bind:this={trigger}>Internal Trigger</button>
  </Trigger>
</Modal>

<button on:click={() => trigger.click()}>External Trigger</button>
```
