### ISSUE TITLE
Console message

### ISSUE THREAD

**Issue by artneo-io** [sharu725/sv-popup#5]
When I run `npm run dev` this warning is showing up:

![console-message](https://user-images.githubusercontent.com/17693529/227540070-02ed5c5d-1bfd-4d5c-ae64-99208be9e860.png)

**Comment by artneo-io** [comment]
Thank you so much for updating it @sharu725! I installed your plugin again with `npm i -D sv-popup`, but the message is still showing up. Is there something else that I need to do? Thanks!

![message](https://user-images.githubusercontent.com/17693529/228216943-9455f6f0-6776-4986-91c2-023beb7e2cf0.png)

**Comment by sharu725** [comment]
Can you check if this line is present on running `npm list`

```
+-- sv-popup@0.5.0
```

**Comment by artneo-io** [comment]
Hmmm it's saying `sv-popup@0.2.5`. How do I update it?

**Comment by sharu725** [comment]
Try `npm i -D sv-popup@latest`

**Comment by artneo-io** [comment]
Awesome, it worked @sharu725! Thank you a lot! 🙂
